name: xnorkl in the middle
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
### include sass, an extended css

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
